/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginsystem;

import javax.swing.*;

/**
 *
 * @author hhwl
 */
public class LoginSystem extends javax.swing.JFrame {

	private final RegistrationSystem regSys;
	private String resetUsername; // prevent redundent storage access when retrieving security question

	/**
	 * Creates new form LoginSystem
	 */
	public LoginSystem() {
		this.regSys = new RegistrationSystem(this);
		this.setIconImage(new ImageIcon("./icon.png").getImage());
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        loginUserLabel = new javax.swing.JLabel();
        loginPassLabel = new javax.swing.JLabel();
        loginUserField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        loginPassField = new javax.swing.JPasswordField();
        login2FALabel = new javax.swing.JLabel();
        login2FAField = new javax.swing.JPasswordField();
        signupPanel = new javax.swing.JPanel();
        signupUserLabel = new javax.swing.JLabel();
        signupUserField = new javax.swing.JTextField();
        signupPhoneLabel = new javax.swing.JLabel();
        signupPhoneField = new javax.swing.JTextField();
        signupEmailLabel = new javax.swing.JLabel();
        signupEmailField = new javax.swing.JTextField();
        signupPassLabel = new javax.swing.JLabel();
        signupPassField = new javax.swing.JPasswordField();
        signupRepeatLabel = new javax.swing.JLabel();
        signupRepeatField = new javax.swing.JPasswordField();
        signupQuestionLabel = new javax.swing.JLabel();
        signupQuestionField = new javax.swing.JTextField();
        signupAnswerLabel = new javax.swing.JLabel();
        signupAnswerField = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        resetPanel = new javax.swing.JPanel();
        resetUserLabel = new javax.swing.JLabel();
        resetUserField = new javax.swing.JTextField();
        resetPhoneLabel = new javax.swing.JLabel();
        resetPhoneField = new javax.swing.JTextField();
        resetEmailLabel = new javax.swing.JLabel();
        resetEmailField = new javax.swing.JTextField();
        resetPassLabel = new javax.swing.JLabel();
        resetPassField = new javax.swing.JPasswordField();
        resetRepeatLabel = new javax.swing.JLabel();
        resetRepeatField = new javax.swing.JPasswordField();
        resetQuestion = new javax.swing.JLabel();
        resetAnswerLabel = new javax.swing.JLabel();
        resetAnswerField = new javax.swing.JTextField();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login System");
        setName("Login System"); // NOI18N
        setResizable(false);

        loginUserLabel.setText("Password");

        loginPassLabel.setText("Username");

        loginButton.setBackground(new java.awt.Color(51, 102, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Log in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        login2FALabel.setText("2FA Code");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(loginButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(login2FALabel)
                    .addComponent(loginUserLabel)
                    .addComponent(loginPassLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(loginUserField)
                        .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(login2FAField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginPassLabel))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUserLabel)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login2FALabel)
                    .addComponent(login2FAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(74, 74, 74))
        );

        tabs.addTab("Login", loginPanel);

        signupUserLabel.setText("Username");

        signupPhoneLabel.setText("Phone Number");

        signupEmailLabel.setText("Email Address");

        signupPassLabel.setText("Password [i]");

        signupRepeatLabel.setText("Repeat Password");

        signupQuestionLabel.setText("Security Question");

        signupAnswerLabel.setText("Security Answer");

        signupButton.setBackground(new java.awt.Color(51, 102, 255));
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupPanelLayout = new javax.swing.GroupLayout(signupPanel);
        signupPanel.setLayout(signupPanelLayout);
        signupPanelLayout.setHorizontalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(signupButton))
                    .addGroup(signupPanelLayout.createSequentialGroup()
                        .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupRepeatLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupPassLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupQuestionLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupAnswerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signupUserLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(signupUserField)
                            .addComponent(signupAnswerField)
                            .addComponent(signupQuestionField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupEmailField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupPassField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signupRepeatField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        signupPanelLayout.setVerticalGroup(
            signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupUserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupPassLabel)
                    .addComponent(signupPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupRepeatLabel)
                    .addComponent(signupRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupQuestionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupQuestionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupAnswerLabel))
                .addGap(18, 18, 18)
                .addComponent(signupButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tabs.addTab("Signup", signupPanel);

        resetUserLabel.setText("Username");

        resetUserField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                resetUserFieldFocusLost(evt);
            }
        });

        resetPhoneLabel.setText("Phone Number");

        resetPhoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                resetPhoneFieldFocusLost(evt);
            }
        });

        resetEmailLabel.setText("Email Address");

        resetEmailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                resetEmailFieldFocusLost(evt);
            }
        });

        resetPassLabel.setText("New Password [i]");

        resetRepeatLabel.setText("Repeat Password");

        resetQuestion.setText("Question: ");

        resetAnswerLabel.setText("Answer:");

        resetButton.setBackground(new java.awt.Color(51, 102, 255));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Confirm");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPanelLayout = new javax.swing.GroupLayout(resetPanel);
        resetPanel.setLayout(resetPanelLayout);
        resetPanelLayout.setHorizontalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resetPanelLayout.createSequentialGroup()
                        .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetRepeatLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetPassLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetPhoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetUserLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resetUserField)
                            .addComponent(resetEmailField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetPassField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetRepeatField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(resetPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(resetPanelLayout.createSequentialGroup()
                                .addComponent(resetAnswerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resetQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(resetPanelLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(resetButton)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        resetPanelLayout.setVerticalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetUserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetPhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetEmailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPassLabel)
                    .addComponent(resetPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetRepeatLabel)
                    .addComponent(resetRepeatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(resetQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetAnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetAnswerLabel))
                .addGap(18, 18, 18)
                .addComponent(resetButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tabs.addTab("Reset Password", resetPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        tabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		String username = loginUserField.getText();
		String password = String.valueOf(loginPassField.getPassword());
		String twoFACode = String.valueOf(login2FAField.getPassword());
		if (regSys.login(username, password, twoFACode)) {
			clearFields();
		}
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
		String username = signupUserField.getText();
		String password = String.valueOf(signupPassField.getPassword());
		String repeat = String.valueOf(signupRepeatField.getPassword());
		String email = signupEmailField.getText();
		String phone = signupPhoneField.getText();
		String securityQuestion = signupQuestionField.getText();
		String securityAnswer = signupAnswerField.getText();
		if (!password.equals(repeat)) {
			regSys.showError("Passwords do not match!!!");
			return;
		}
		if (regSys.register(username, password, email, phone, securityQuestion, securityAnswer)) {
			clearFields();
		}
    }//GEN-LAST:event_signupButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
		String username = resetUserField.getText();
		String newPass = String.valueOf(resetPassField.getPassword());
		String repeat = String.valueOf(resetRepeatField.getPassword());
		String email = resetEmailField.getText();
		String phone = resetPhoneField.getText();
		String securityAnswer = signupAnswerField.getText();
		if (!newPass.equals(repeat)) {
			regSys.showError("Passwords do not match!!!");
			return;
		}
		if (regSys.resetPassword(username, newPass, phone, email, securityAnswer)) {
			clearFields();
		}
    }//GEN-LAST:event_resetButtonActionPerformed

    private void resetEmailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetEmailFieldFocusLost
		updateSecurityQuestion();
    }//GEN-LAST:event_resetEmailFieldFocusLost

    private void resetPhoneFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetPhoneFieldFocusLost
		updateSecurityQuestion();
    }//GEN-LAST:event_resetPhoneFieldFocusLost

    private void resetUserFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetUserFieldFocusLost
		updateSecurityQuestion();
    }//GEN-LAST:event_resetUserFieldFocusLost

	/**
	 * Update security question label
	 */
	public void updateSecurityQuestion() {
		String username = resetUserField.getText();
		String email = resetEmailField.getText();
		String phone = resetPhoneField.getText();
		// prevent retrieving question again when username hasn't changed
		if (username.equals(resetUsername)) {
			return;
		}
		// exit if fields empty
		if (username.length() == 0 || email.length() == 0 || phone.length() == 0) {
			return;
		}
		resetQuestion.setText("Question: " + regSys.retrieveSecurityQuestion(username, email, phone));
		resetUsername = username;
	}

	/**
	 * Clear all input after a success
	 */
	public void clearFields() {
		login2FAField.setText("");
		loginPassField.setText("");
		resetPassField.setText("");
		resetRepeatField.setText("");
		signupPassField.setText("");
		signupRepeatField.setText("");
		loginUserField.setText("");
		resetAnswerField.setText("");
		resetEmailField.setText("");
		resetPhoneField.setText("");
		resetUserField.setText("");
		signupAnswerField.setText("");
		signupEmailField.setText("");
		signupPhoneField.setText("");
		signupQuestionField.setText("");
		signupUserField.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		// set modern look
		try {
			UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
		} catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new LoginSystem().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField login2FAField;
    private javax.swing.JLabel login2FALabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JLabel loginPassLabel;
    private javax.swing.JTextField loginUserField;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JTextField resetAnswerField;
    private javax.swing.JLabel resetAnswerLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField resetEmailField;
    private javax.swing.JLabel resetEmailLabel;
    private javax.swing.JPanel resetPanel;
    private javax.swing.JPasswordField resetPassField;
    private javax.swing.JLabel resetPassLabel;
    private javax.swing.JTextField resetPhoneField;
    private javax.swing.JLabel resetPhoneLabel;
    private javax.swing.JLabel resetQuestion;
    private javax.swing.JPasswordField resetRepeatField;
    private javax.swing.JLabel resetRepeatLabel;
    private javax.swing.JTextField resetUserField;
    private javax.swing.JLabel resetUserLabel;
    private javax.swing.JTextField signupAnswerField;
    private javax.swing.JLabel signupAnswerLabel;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField signupEmailField;
    private javax.swing.JLabel signupEmailLabel;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JPasswordField signupPassField;
    private javax.swing.JLabel signupPassLabel;
    private javax.swing.JTextField signupPhoneField;
    private javax.swing.JLabel signupPhoneLabel;
    private javax.swing.JTextField signupQuestionField;
    private javax.swing.JLabel signupQuestionLabel;
    private javax.swing.JPasswordField signupRepeatField;
    private javax.swing.JLabel signupRepeatLabel;
    private javax.swing.JTextField signupUserField;
    private javax.swing.JLabel signupUserLabel;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
